vich_uploader:
    db_driver: orm

    mappings:
        recipe_images:
            uri_prefix: '%app.path.recipe_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.recipe_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
